---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: devops-example-ui
  labels:
    app: devops-example-ui
spec:
  minReplicas: 2
  maxReplicas: 6
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devops-example-ui
  targetCPUUtilizationPercentage: 80
