apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-example-ui
  labels:
    app: devops-example-ui
spec:
  selector:
    matchLabels:
      app: devops-example-ui
  template:
    metadata:
      labels:
        app: devops-example-ui
    spec:
      containers:
      - name: devops-example-ui
        image: kster/devops-example-ui
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 80m
            memory: 128Mi

